### ISSUE TITLE
"git checkout" vs "git fetch"

### ISSUE THREAD

**Issue by staylor12** [githubteacher/flaming-octo-meme#136]
If i do a "git checkout master" and my local copy is out of date, does it fetch the changes automatically, or merely let me know that I'm behind, requiring me to perform a "git fetch"?

**Comment by githubstudent** [comment]
No - git checkout does not update the local branch. It only checks out the local copy of the branch as it currently exists. This is due to the distributed nature of git. You will need to explicitly tell git you want it to fetch from the remote!

**Comment by staylor12** [comment]
Thanks!
